apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: spring-template-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: conjur-secret-store
    kind: ClusterSecretStore
  target:
    name: spring-template-secrets
    creationPolicy: Owner
  data:
    - secretKey: db-url
      remoteRef:
        key: spring-template-starter/db-url
    - secretKey: db-username
      remoteRef:
        key: spring-template-starter/db-username
    - secretKey: db-password
      remoteRef:
        key: spring-template-starter/db-password
    - secretKey: actuator-username
      remoteRef:
        key: spring-template-starter/actuator-username
    - secretKey: actuator-password
      remoteRef:
        key: spring-template-starter/actuator-password
