apiVersion: v1
kind: Service
metadata:
  name: spring-template-starter
  labels:
    app.kubernetes.io/name: spring-template-starter
spec:
  selector:
    app.kubernetes.io/name: spring-template-starter
  ports:
    - name: http
      port: 80
      targetPort: 8080
